"""Allow NULL condition for non-PRICE alerts

Revision ID: 25e65135c38c
Revises: 8bce096e6161
Create Date: 2026-04-02 04:45:25.249070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '25e65135c38c'
down_revision: Union[str, None] = '8bce096e6161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'condition',
               existing_type=postgresql.ENUM('GREATER_THAN', 'LESS_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL', 'PERCENTAGE_CHANGE', name='alertcondition'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFETY: Before making condition NOT NULL, update any NULL values to GREATER_THAN
    # This ensures downgrade succeeds even if there are NULL values in the database
    op.execute(
        sa.text("UPDATE alerts SET condition = 'GREATER_THAN' WHERE condition IS NULL")
    )
    
    # Now safely alter the column to NOT NULL
    op.alter_column('alerts', 'condition',
               existing_type=postgresql.ENUM('GREATER_THAN', 'LESS_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL', 'PERCENTAGE_CHANGE', name='alertcondition'),
               nullable=False)
    # ### end Alembic commands ###

